### PR TITLE
Avoid using absolute path with tar command when archiving

### LINKED ISSUE #162: New Tar Upload Not Expanding As Expected
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 2.1.2
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time?  EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? Not setup to be able to try this

### Issue description

It looks like the switch to Tar is causing a folder to not expand as expected. https://github.com/bitrise-steplib/steps-deploy-to-bitrise-io/pull/161

Instead of a folder like `/var/folder/test` uploading and then expanding to `/var/folder/test` it is now expanding into `/var/folder/test/var/folder/test`

### Bitrise info

- Build URL: https://app.bitrise.io/build/e026e783-e266-461c-bfc8-6619baa23f0d
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _NO_
- Log: 

<details>
  <pre>

Switching to workflow: run_tests_iphone_14
+------------------------------------------------------------------------------+
| (0) script@1                                                                 |
+------------------------------------------------------------------------------+
| id: script                                                                   |
| version: 1.2.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2022-10-19T20:56:24Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
total 0
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 .
0 drwx------  3 vagrant  staff  96 Oct 19 20:56 ..
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 var
/var/folders/gx/0jx30grn0xqb3pvktj4731840000gn/T/_artifact_pull1873648077/test_bundle1311517843
total 0
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 .
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 ..
0 drwxr-xr-x  3 vagrant  staff  96 Oct 19 20:56 folders
ls: /var/folders/gx/0jx30grn0xqb3pvktj4731840000gn/T/_artifact_pull1873648077/test_bundle1311517843/var/folders/gx/0jx30grn0xqb3pvktj4731840000gn/T/_artifact_pull1873648077/test_bundle1311517843: No such file or directory
|                              
  </pre>
</details>

### Steps to reproduce

1. Have a deploy to bitrise step like:
```
      - xcode-build-for-test:
          inputs:
            - destination: generic/platform=iOS Simulator
      - deploy-to-bitrise-io@2.1.1:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_TEST_BUNDLE_PATH:BITRISE_TEST_BUNDLE_PATH'
```

Then another workflow like:

```
  run_tests_iphone_14:
    steps:
      - pull-intermediate-files@1:
          inputs:
            - artifact_sources: build-and-test.test_build
      - xcode-test-without-building:
          inputs:
            - xctestrun: '$BITRISE_TEST_BUNDLE_PATH/$TEST_BUNDLE_NAME'
            - destination: platform=iOS Simulator,name=iPhone 14,OS=16
      - deploy-to-bitrise-io@2:
          inputs:
            - pipeline_intermediate_files: '$BITRISE_XCRESULT_PATH:BITRISE_IPHONE_14_TEST_XCRESULT_PATH'
```

### PR DESCRIPTION
**Pull request by vshah23**
### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [ ] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *PATCH* [version update](https://semver.org/)

### Context

Fixes #162 (SWAT-816)

The `tar` command can't change the pathname of the files when unarchiving so we need to avoid using the absolute path of the directory. Hence we set the working directory as the parent directory of the directory we're archiving via the `-C` argument when invoking `tar`.

https://docstore.mik.ua/orelly/unix/upt/ch20_10.htm

https://stackoverflow.com/a/3035446

### Changes

We now execute `tar cf /path/of/output.tar -C /path/of/directory_to_archive/ .`

The `-C` argument makes `tar` switch to the given directory before archiving and we pass `.` in order to denote that all files in that directory should be archived.

### Investigation details

Originally tried to just set the working directory of the command, but that led to an extra parent directory when unarchiving.

Example:

```
tar cf my_directory.tar my_directory
tar xf my_directory.tar

output:
my_directory
   --- my_file
   --- my_file
   --- my_file
```

After extracting we have the files we want contained in `my_directory` which is not what the subsequent pull pipeline intermediates step was expecting.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -299,12 +299,22 @@ func collectFilesToDeploy(absDeployPth string, config Config, tmpDir string) (fi
...
 	fmt.Println()
-	log.Infof("Compressing directory...")
+	log.Infof("Archiving directory...")
+
+	// Note: The tar command can't change the pathname of the files
+	// when unarchiving so we need to avoid using the absolute path
+	// of the directory. Hence we set the working directory as the
+	// parent directory of the directory we're archiving.
+	// https://docstore.mik.ua/orelly/unix/upt/ch20_10.htm
+	workDir := strings.TrimRight(sourceDirPath, "/")
```
Comment (Grayson) [inline main.go:309]: Out of curiosity, how does this affect the `Dir` and `Base` functions below?  I'd expect that file path algorithms are savvy enough to ignore trailing `/` where appropriate.

**Review by Grayson — DISMISSED** [review]

File: main.go (hunk 1 above)
Comment (vshah23) [reply main.go:309]: I tested in macOS and it made a difference whether or not there was a slash at the end.

Example:
Parent directory we want: `/var/folder/`
Target directory: `/var/folder/test`
Output of `Dir`: `/var/folder/`

Example2:
Parent directory we want: `/var/folder/`
Target directory: `/var/folder/test/`
Output of `Dir`: `/var/folder/test`

Comment (vshah23) [reply main.go]: Got rid of this in favor of using the `-C` argument with the `tar` command.

**Review by godrei — APPROVED** [review]
